export default [
    {
      "_id": "A101",
      "title": "Propulsion Assignment",
      "course": "RS101",
      "moduleType": "Multiple Modules",
      "releaseDateTime": "2025-05-02T00:00",
      "dueDateTime": "2025-05-10T23:59",
      "points": 100,
      "description": "Analyze propulsion systems and their efficiency.",
      "status": "Published",
      "assignTo": "Everyone",
      "assignmentGroup": "ASSIGNMENTS",
      "displayType": "Percentage",
      "submissionType": "Online"
    },
    {
      "_id": "A102",
      "title": "Combustion Analysis",
      "course": "RS101",
      "moduleType": "Multiple Modules",
      "releaseDateTime": "2025-05-03T00:00",
      "dueDateTime": "2025-05-11T23:59",
      "points": 100,
      "description": "Perform combustion analysis for various fuels.",
      "status": "Draft",
      "assignTo": "Everyone",
      "assignmentGroup": "ASSIGNMENTS",
      "displayType": "Letter",
      "submissionType": "In-person"
    },
    {
      "_id": "A103",
      "title": "Nozzle Design Project",
      "course": "RS101",
      "moduleType": "Multiple Modules",
      "releaseDateTime": "2025-05-04T00:00",
      "dueDateTime": "2025-05-12T23:59",
      "points": 100,
      "description": "Design and optimize nozzle configurations.",
      "status": "Published",
      "assignTo": "Everyone",
      "assignmentGroup": "PROJECT",
      "displayType": "Percentage",
      "submissionType": "Online"
    },
    {
      "_id": "A201",
      "title": "Aerodynamics Quiz",
      "course": "RS102",
      "moduleType": "Multiple Modules",
      "releaseDateTime": "2025-05-05T00:00",
      "dueDateTime": "2025-05-13T23:59",
      "points": 100,
      "description": "Test your knowledge of aerodynamics principles.",
      "status": "Published",
      "assignTo": "Everyone",
      "assignmentGroup": "QUIZZES",
      "displayType": "Percentage",
      "submissionType": "Online"
    },
    {
      "_id": "A202",
      "title": "Flow Analysis",
      "course": "RS102",
      "moduleType": "Multiple Modules",
      "releaseDateTime": "2025-05-06T00:00",
      "dueDateTime": "2025-05-14T23:59",
      "points": 100,
      "description": "Analyze subsonic and supersonic flow patterns.",
      "status": "Draft",
      "assignTo": "Everyone",
      "assignmentGroup": "ASSIGNMENTS",
      "displayType": "Letter",
      "submissionType": "In-person"
    },
    {
      "_id": "A203",
      "title": "Heating Analysis",
      "course": "RS102",
      "moduleType": "Multiple Modules",
      "releaseDateTime": "2025-05-07T00:00",
      "dueDateTime": "2025-05-15T23:59",
      "points": 100,
      "description": "Evaluate aerodynamic heating effects.",
      "status": "Published",
      "assignTo": "Everyone",
      "assignmentGroup": "PROJECT",
      "displayType": "Percentage",
      "submissionType": "Online"
    }
]